{application,emqttd_plugin_pgsql,
             [{description,"emqttd PostgreSQL Plugin"},
              {vsn,"1.1"},
              {registered,[]},
              {modules,[emqttd_acl_pgsql,emqttd_auth_pgsql,
                        emqttd_plugin_pgsql,emqttd_plugin_pgsql_app,
                        emqttd_plugin_pgsql_sup]},
              {applications,[kernel,stdlib,epgsql,ecpool]},
              {mod,{emqttd_plugin_pgsql_app,[]}},
              {env,[]}]}.
